service: email-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10

functions:
  api:
    timeout: 30
    handler: handlers/send_email.send_email
    events:
      - http: 
          path: '/send_email'
          method: post
          cors: true
          integration: lambda

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline

